### ISSUE TITLE
I can create a profile with a text editor and a git client

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/profiles#1]
Create a simple profile in a "profile repository".

```
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: nginx-profile
spec:
  description: <insert description>
  maturity: alpha
  owner: WeaveWorks <gitops@weave.works>
  version: v0.0.1
  artifacts:
    # An artifact references a Helm chart, a local path, or a remote Profile.
    # version, url go together, and path is mutually exclusive with the url/version
    - name: nginx-server
      path: nginx/chart # <- relative to the profile.yaml, this gets the example nginx Helm chart we want to deploy.
```

**Comment by aclevername** [comment]
>     # An artifact references a Helm chart, a local path, or a remote Profile.
>     # version, url go together, and path is mutually exclusive with the url/version
>     - name: nginx-server
>       path: nginx/chart # <- relative to the profile.yaml, this gets the example nginx Helm chart we want to deploy.
> ```

@bigkevmcd do you mean [helm release](https://docs.fluxcd.io/projects/helm-operator/en/1.0.0-rc9/references/helmrelease-custom-resource.html#helmrelease-custom-resource) instead of chart?

**Comment by aclevername** [comment]
> No, I think the directory contains the Helm chart, I think it's the responsibility of the bit we build to get this into HelmRelease.

I might be confused, but I don't see how having the helm chart itself in the artefacts directory is useful as the `HelmRelease` references the remote location, [example](https://docs.fluxcd.io/projects/helm-operator/en/1.0.0-rc9/references/helmrelease-custom-resource.html)
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rabbit
  namespace: default
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: rabbitmq
    version: 3.3.6
```

I had imagined it would look like this:
```
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: nginx-profile
spec:
  ...
   artifacts
    - name: nginx-server
      chart:
        repository: https://kubernetes-charts.storage.googleapis.com/
        name: rabbitmq
        version: 3.3.6
     - name: some-other-artifact
       path: ./artifacts/local/yaml/path
```

WDYT?
