### ISSUE TITLE
You should not be able to recursively nest profiles

### ISSUE THREAD

**Issue by aclevername** [weaveworks/profiles#100]
currently we only check 1 deep to see if the current profiles is artifacting itself. Lets add a check to ensure that no matter how many profiles down the recursion occurs it is caught.

E.g.:
Profile `https://github.com/weaveworks/nginx-profile` on branch `main`
```
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: nginx
spec:
  description: Profile for deploying nginx
  version: v0.0.1
  artifacts:
    - name: nested-profile
      kind: Profile
      profile:
        url: https://github.com/weaveworks/nginx-profile
        branch: helm-artifact     
```

Where `helm-artifact` is:
```
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: nginx
spec:
  description: Profile for deploying nginx
  version: v0.0.1
  artifacts:
    - name: nested-profile
      kind: Profile
      profile:
        url: https://github.com/weaveworks/nginx-profile
        branch: foo
```

Where `foo` is:
```
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: nginx
spec:
  description: Profile for deploying nginx
  version: v0.0.1
  artifacts:
    - name: nested-profile
      kind: Profile
      profile:
        url: https://github.com/weaveworks/nginx-profile
        branch: main
```

This should error out as we are installing profile  `https://github.com/weaveworks/nginx-profile` on branch `main` that eventually contains itself as an artifact
