### ISSUE TITLE
Add support for installing profiles from a tag

### ISSUE THREAD

**Issue by aclevername** [weaveworks/profiles#102]
**What feature/behavior/change do you want?**

## Placeholder, may change depending on the output of https://github.com/weaveworks/profiles/issues/76
Follow up to https://github.com/weaveworks/profiles/issues/76, now we have documented and understand our approach for tagging we need to add support for getting a profile from a tag. Currently a subscription looks like:
```
apiVersion: weave.works/v1alpha1
kind: ProfileSubscription
metadata:
  name: nginx-profile-test
  namespace: default
spec:
  profileURL: https://github.com/weaveworks/nginx-profile
  branch: main
```

We use the `profileURL` and `branch` to fetch the profile. This story is to introduce a new alternative to the `branch` field, `tag`

```
apiVersion: weave.works/v1alpha1
kind: ProfileSubscription
metadata:
  name: nginx-profile-test
  namespace: default
spec:
  profileURL: https://github.com/weaveworks/nginx-profile
  tag: nginx/1.2.3
```

**Why do you want this feature?**
So I can install a profile from a tag
