### ISSUE TITLE
Add support for installing a profile from a tag or path

### ISSUE THREAD

**Issue by aclevername** [weaveworks/profiles#110]
As part of https://github.com/weaveworks/profiles/pull/108 we agreed how we will implement multi-profile repos and tagging. We now need to update the controller and profile subscription to pull from these repos. We now need to update the profile subscription to match:

## Version

Version (git tag) workflow:
```
apiVersion: weave.works/v1alpha1
kind: ProfileSubscription
metadata:
  name: foo-test
  namespace: default
spec:
  profileURL: https://github.com/weaveworks/weaveworks-profiles
  version: foo/v0.1.2
```

This should result in the `foo` directory in git tag `foo/v0.1.2` being the source of truth for this profile

## Branch
Branch & path base workflow:
```
apiVersion: weave.works/v1alpha1
kind: ProfileSubscription
metadata:
  name: bar-test
  namespace: default
spec:
  profileURL: https://github.com/weaveworks/weaveworks-profiles
  branch: main
  path: bar/
```
  
  This should result in the `bar` directory on branch `main` being the source of truth for this profile
