### ISSUE TITLE
Validate profile version before adding them to the catalog

### ISSUE THREAD

**Issue by aclevername** [weaveworks/profiles#129]
When someone tries to create a profile thats invalid it should not get added to the catalog

## Example:
The below catalog entry should get rejected because it does not have a valid `version`
```
apiVersion: weave.works/v1alpha1
kind: ProfileCatalogSource
metadata:
  name: nginx-catalog
spec:
  profiles:
    - name: weaveworks-nginx
      description: This installs nginx.
      version: totally!not?semver
      url: https://github.com/weaveworks/profiles-examples
      maintainer: weaveworks (https://github.com/weaveworks/profiles)
      prerequisites:
      - Kubernetes 1.18+
```

Not sure what fields outside of `version` we want to check :shrug: 

## Implementation thoughts
Two reasonable approaches:
1. Validating webhook, checks each entry and rejects any that are malformed. This lets the user get immeditate feedback about the failures
2. The controller simply ignores any malformed profiles  
3. Regex matching as part of the CRD https://book.kubebuilder.io/reference/markers/crd-validation.html
