### ISSUE TITLE
Support for discovering profiles in a repository

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#145]
Follow up from https://github.com/weaveworks/profiles/issues/127

Building a catalog currently requires manual addition of CatalogSources. This is a pain when adding a profile repo which contains multiple profiles with multiple tags.

The linked spike demonstrates how we can take a profile repo url and automatically detect new profiles and their tags and add them to the catalog.

```yaml
apiVersion: weave.works/v1alpha1
kind: ProfileCatalogSource
metadata:
  name: nginx-catalog
spec:
  repo: https://github.com/aclevername/profiles-examples
  secretRef:
     name: blueberry
```

Note: this only handles the first half of the work mentioned in the spike. Just fetch the profiles+tags of a given url, do not worry about watching repos for new tags there will be another story for this.
