### ISSUE TITLE
Support for single-profile repositories

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/profiles#150]
**What feature/behavior/change do you want?**

While we have good support for multiple profile repositories, with the `name/tag` approach, we expect customers will want simpler profile repositories.

We should support single profile repositories, with simple SemVer tagging.

**Why do you want this feature?**

Some users will want the simpler tagging of profiles (perhaps because they only have a very small number of profiles).

**Comment by aclevername** [comment]
@bigkevmcd do we imagine the `profile.yaml` lives at the top level directory in this case? or still in a `profile-name/profile.yaml`

**Comment by bigkevmcd** [comment]
I'd think at the top-level.

**Comment by aclevername** [comment]
Currently a catalog entry looks like:
```yaml
apiVersion: weave.works/v1alpha1
kind: ProfileCatalogSource
metadata:
  name: nginx-catalog
spec:
  profiles:
    - name: weaveworks-nginx
      description: This installs nginx.
      version: v0.1.0
      url: https://github.com/weaveworks/profiles-examples
      maintainer: weaveworks (https://github.com/weaveworks/profiles)
      prerequisites:
      - Kubernetes 1.18+
```

We currently have it hardcoded behind that scenes that installing the above profiles results in `profile.name + "/" + profile.version` to discover that tag, and that `profile.name` is also the folder.

Now we want to support specifying one where the `tag` is equal to the `profile.version` and the `profile.yaml` is at the top level directory. I suggest we change it so that it now looks like:
```yaml
apiVersion: weave.works/v1alpha1
kind: ProfileCatalogSource
metadata:
  name: nginx-catalog
spec:
  profiles:
    - name: weaveworks-nginx
      description: ...
      version: v0.1.0 # optional, we could remove this and infer from tag everywhere
      tag: weaveworks-nginx/v0.1.0
      url: https://github.com/weaveworks/profiles-examples
      maintainer: ...
      prerequisites: ...
    - name: other-top-level
      description: ...
      version: v0.1.0
      tag: v0.1.0
      url: https://github.com/weaveworks/top-level-example
      maintainer: ...
      prerequisites: ...
```


`tag` would be used internally and not shown to the user. If a tag was `name/semver` than we know its referring to a multi-repo profile. if its just `semver` we know its a top level profile.

 We could remove the `version` field and let pctl figure it out from the tag, might be less confusing.
