### ISSUE TITLE
[Spike] How can we define dependency ordering

### ISSUE THREAD

**Issue by aclevername** [weaveworks/profiles#196]
**What feature/behavior/change do you want?**
I want to be able to define dependecy ordering between artifacts. E.g.:
- A profile consists of charts A and B. B needs to be installed before A. Help.

Can this be done?

hint: look at `dependsOn` in the kustomize and helm-release docs https://fluxcd.io/docs/components/helm/helmreleases/#helmrelease-dependencies

Outcome:
- Some demo code (if needed)
- Write up of the findings in a proposal doc

**Comment by aclevername** [comment]
## What do we want?
As a user of profile, I want to be able to ensure that contents of my profile are deployed in a particular order, to ensure that my artifacts deploy successfully. A common example of this is a profile that deploys a custom resource definition, and some instances of that custom resource. For example if you try to deploy a profile like:

```
apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: example-profile
spec:
  description: example CRD and CR
  maintainer: aclevername
  artifacts:
    - name: folder-1
      kustomize:
        path: folder-1/
    - name: folder-2
      kustomize:
        path: folder-2/
```

`folder-1` contains a instance of a custom resource `Foo`. `folder-2` contains the custom resource definition of `Foo`. If you try to deploy this profile you will get the following error from the gitops repository kustomization resource:
```
flux-system   flux-system   False   validation failed: error: unable to recognize "f4023b8f-6d22-41ea-91fc-41db26cb9eb7.yaml": no matches for kind "Foo" in version "weave.works/v1alpha1"
```
