### ISSUE TITLE
I can subscribe to a profile with a helm release (nginx) in it

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/profiles#2]
As a user, I want to trigger the deployment of a Helm chart from a profile, by subscribing to a specific version of a profile.

```yaml
apiVersion: ...
kind: ProfileSubscription
spec:
    profileURL: https://github.com/testing/testing.git # <- profile.yaml
```

Use kubectl to apply this yaml, and this should trigger a `HelmRelease` with chart from the profile.

This does not require any configuration.
