### ISSUE TITLE
As a profile author I want to be able to set dependency ordering between artifacts of the same kind

### ISSUE THREAD

**Issue by aclevername** [weaveworks/profiles#214]
Prior spike https://github.com/weaveworks/profiles/issues/196

**What feature/behavior/change do you want?**
I want to be able to set dependency ordering between my charts or kustomizations. This is *ONLY* for artiacts of the same kind, e.g. helm chart depends on another helm chart, or kustomization depends on another kustomization. For a chart <-> kustomization relationship see #215.
**Why do you want this feature?**
I have a chart for deploying a CRD, and a chart that creates some instances of the CRD. I need the CRD to exist before I can create my instances, so I want to define that it should get deployed first.

## Proposed changes
Adding an additional `dependsOn` field that takes a list of artifact names:
```
spec:
  artifacts:
    - name: crd-chart
      chart:
        ...
    - name: instances-chart
      dependsOn: # new
      - name: crd-chart # new
      chart:
        ...
 ```
 
 When the HelmRelease/Kustomization resource gets generated for `instances-chart` it should contain the `dependsOn` fields. [Flux docs](https://fluxcd.io/docs/components/helm/helmreleases/#helmrelease-dependencies)

Example:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: ">=4.0.0 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
      interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: ">=4.0.0 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
      interval: 1m
  dependsOn:
    - name: backend
  ```
