### ISSUE TITLE
As a profile author I want to be able to set dependency ordering on nested profiles

### ISSUE THREAD

**Issue by aclevername** [weaveworks/profiles#227]
**What feature/behavior/change do you want?**
Follow up from #214 #215. Here we added support for specifying `dependsOn` in your profile definition to enforce dependency ordering. For example we currently support this:
```
apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: weaveworks-nginx
spec:
  description: Profile for deploying nginx
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: nginx-deployment
      kustomize:
        path: nginx/deployment
      dependsOn:
      - name: `nginx-chart`
    - name: nginx-chart
      chart:
        url: https://charts.bitnami.com/bitnami
        name: nginx
        version: "9.3.0"
```

However we don't support specifying a nested profile artifact in `dependsOn`. For example this following isn't supported:
```
apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: weaveworks-nginx
spec:
  description: Profile for deploying nginx
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: nginx-deployment
      kustomize:
        path: nginx/deployment
      dependsOn:
      - name: nested-profile
    - name: nested-profile
      profile:
        source:
          url: https://github.com/weaveworks/profiles-examples
          tag: bitnami-nginx/v0.0.1
```

Lets add support for specifying a nested profile as a dependency. Currently we "flattern" artifacts in memory, and only distinguish them by having them in separate directory structures in the generated output. So this new feature might require a change to how we handle this abstraction in the code.
