### ISSUE TITLE
[Proposal] Providing values for multiple artifacts at once

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/profiles#264]
# Proposal for applying values to N artifacts

Spike: https://github.com/weaveworks/profiles/issues/197

## Adding default values to the profiles definition spec

Currently:

```go
// ProfileDefinitionSpec defines the desired state of ProfileDefinition
type ProfileDefinitionSpec struct {
	ProfileDescription `json:",inline"`
	// Artifacts is a list of Profile artifacts
	Artifacts []Artifact `json:"artifacts,omitempty"`
}
```

This proposal extends this definition with a DefaultValue or a Value section.

```go
// ProfileDefinitionSpec defines the desired state of ProfileDefinition
type ProfileDefinitionSpec struct {
	ProfileDescription `json:",inline"`
	// Artifacts is a list of Profile artifacts
	Artifacts []Artifact `json:"artifacts,omitempty"`
    // Values define values which should be applied to all artifacts within this spec
    // +optional
    Values string `json:"values,omitempty"
}
```

## Adding values during `add`

Providing a flag during `add` operation such as:

```
pctl add --values '{valueA: {server: ClusterIP}}' weaveworks/nginx
```

That's minified YAML in there.

This will insert a DefaultValues "section" into every chart artifact before writing it so that it gets a value definition
as if it had a defaultValue section like this:

```yaml
  artifacts:
    - name: bitnami-nginx
      chart:
        url: https://charts.bitnami.com/bitnami
        name: nginx
        version: "8.9.1"
        defaultValues: |
          valueA:
            server: ClusterIP
```

This has the upside that it doesn't require spec change and can be done entirely in pctl.
