### ISSUE TITLE
I can customize a raw yaml file with Kustomize

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/profiles#4]
# TODO more discussion needed

Kustomize CRD: https://toolkit.fluxcd.io/components/kustomize/kustomization/

```
apiVersion: weave.works/v1alpha1
kind: ProfileSubscription
metadata:
  name: nginx-profile-test
  namespace: default
spec:
  profileURL: https://github.com/weaveworks/nginx-profile
  branch: yaml
  patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: podinfo
    patch:
    - op: add
      path: /metadata/annotations/key
      value: value
 ```
