### ISSUE TITLE
I can install a Profile that contains a Profile

### ISSUE THREAD

**Issue by aclevername** [weaveworks/profiles#68]
**What feature/behavior/change do you want?**
Add *basic* support for having a profile as an artifact

e.g. Profile A:
```
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: profile-A
spec:
  description: Profile for deploying nginx
  version: v0.0.1
  artifacts:
    - name: nginx-server
      path: nginx/chart
      kind: HelmChart
```

Profile B:
```
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: profile-B
spec:
  description: Profile for deploying nginx
  version: v0.0.1
  artifacts:
    - name: nginx-server
      profile:
        url: github.com/weaveworks/profile-a
        branch: main
      kind: Profile
    - name: nginx-consumer
      path: some/helm/chart
      kind: HelmChart
```

**Why do you want this feature?**
So that I can write more granular re-usable profiles
