### ISSUE TITLE
[Investigate] Is it possible to add a duplicate profile in a catalog source?

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#89]
... and is that a problem?

could i end up with 2 x `cat1/prof1` in my catalog?

**Comment by bigkevmcd** [comment]
This is a good question, I think "no", but what we do to mitigate it is interesting.

**Comment by aclevername** [comment]
If I add this catalog source: 
```
apiVersion: weave.works/v1alpha1
kind: ProfileCatalogSource
metadata:
  name: nginx-catalog
spec:
  profiles:
    - name: weaveworks-nginx
      description: This installs nginx.
      version: 0.0.1
      url: https://github.com/weaveworks/nginx-profile
      maintainer: weaveworks (https://github.com/weaveworks/profiles)
      prerequisites:
      - Kubernetes 1.18+
    - name: weaveworks-nginx
      description: This installs nginx.
      version: 0.0.1
      url: https://github.com/weaveworks/nginx-profile
      maintainer: weaveworks (https://github.com/weaveworks/profiles)
      prerequisites:
      - Kubernetes 1.18+
    - name: some-other-nginx
      description: This installs some other nginx.
      version: 1.0.1
      url: https://github.com/weaveworks/nginx-profile
      maintainer: weaveworks (https://github.com/weaveworks/profiles)
      prerequisites:
      - Kubernetes 1.19+
```

and search I do get two duplicate entrys:

```
pctl search nginx
searching for profiles matching "nginx":
weaveworks-nginx: This installs nginx.
weaveworks-nginx: This installs nginx.
some-other-nginx: This installs some other nginx.
```
